### ISSUE TITLE
Missing textures in 5.0.1

### ISSUE THREAD

**Issue by Visteus** [jpw1991/chebs-necromancy#276] opened 2024-08-10 23:46 UTC
![image](https://github.com/user-attachments/assets/b13c145e-cbbc-45c0-b909-1bde2c0a7a32)
![image](https://github.com/user-attachments/assets/e93da9b1-946d-4669-8b21-f8ef8f85d2e4)
![image](https://github.com/user-attachments/assets/5e1da179-3e0c-4295-98c6-00129e6aacb9)

As seen here, all structures from this mod are now semi-translucent pink silhouettes. The Necks are particularly silly. No errors or otherwise in the logs

**Comment by jpw1991** [comment] 2024-08-11 00:44
Weurgh... are the skeletons ok?

Please run it in Vulkan and tell me if the problem is gone

**Comment by Artificiunm** [comment] 2024-08-12 14:34
I have this exact bug! :0

Skelee bos, totems. item effects have no textures

![image](https://github.com/user-attachments/assets/0c2ae651-c083-4c76-872d-5f2fd0ad6614)


![image](https://github.com/user-attachments/assets/a06d967c-bd6a-47d2-a82f-97581e69cd81)

Let me knoww if there is some mistake on my part ;u;

**Comment by jpw1991** [comment] 2024-08-12 15:28
No it's not your fault. I'll fix it soon. Sorry about that. Please either downgrade or use the Vulkan renderer:

![image](https://github.com/user-attachments/assets/6a8488c0-54a1-4ec9-8030-990fc55ed997)

**Comment by jpw1991** [comment] 2024-08-13 02:19
Fixed in 5.0.2 but you'll still get a few errors in your log, as it's loading in, about `Desired shader compiler platform 4 missing` or whatever unless you run it in Vulkan.

**Closed by jpw1991** 2024-08-13 02:19 UTC
Labels: bug
